In [1]:
import pandas as pd

df = pd.read_csv('./zinc_db/AAAA.txt',sep='\t')

In [2]:
df

,smiles,zinc_id,inchikey,mwt,logp,reactive,purchasable,tranche_name,features
0,CO[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O,4371221,ZBDGHWFPLXXWRD-MOJAZDJTSA-N,164.157,-1.928,0,50,AAAA,NaN
1,C[S@@](=O)CC(N)=O,34310585,TTXPTDCYRCXFHQ-ZETCQYMHSA-N,121.161,-1.150,0,50,AAAA,NaN
2,NC(=O)N[C@@H]1NC(=O)NC1=O,1843030,POJWUDADGALRAB-PVQJCKRUSA-N,158.117,-2.180,0,50,AAAA,"endogenous,world"
3,O=c1[nH]c(O)c(O)c(=O)[nH]1,1847417,YFQOVSGFCVQZSW-UHFFFAOYSA-N,144.086,-1.526,0,50,AAAA,"biogenic,in-vitro"
4,NC(=O)CN1CCC(N)CC1,9256947,JWRVCVWALQWYIJ-UHFFFAOYSA-N,157.217,-1.105,0,50,AAAA,in-vitro
...,...,...,...,...,...,...,...,...,...
3725,N=C(N)NCCC[C@H](N)C(N)=O,1737947,ULEBESPCVWBNIF-BYPYZUCNSA-N,173.220,-1.938,0,50,AAAA,"biogenic,in-vivo"
3726,CNC(=O)COCCN,51864337,YERHKSJQDNTIDQ-UHFFFAOYSA-N,132.163,-1.292,0,50,AAAA,in-vitro
3727,Nc1n[nH]c(N)n1,4118774,PKWIYNIDEDLDCJ-UHFFFAOYSA-N,99.097,-1.031,0,50,AAAA,in-vitro
3728,NCC(N)(CO)CO,19369393,NLXHZMJIVQBDRV-UHFFFAOYSA-N,120.152,-2.373,0,50,AAAA,NaN
3729,N[C@@H]1CS(=O)(=O)C[C@@H]1N,23224603,SHSRKYMXSFBHOU-ZXZARUISSA-N,150.203,-1.931,0,50,AAAA,in-vitro

In [3]:
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
df.sort_values(by='logp')

,smiles,zinc_id,inchikey,mwt,logp,reactive,purchasable,tranche_name,features
1012,[O-][I+3]([O-])([O-])O,1857621909,WXSIPUYRSBVXGK-UHFFFAOYSA-N,191.908,-7.120,0,50,AAAA,NaN
265,B1BBBBBC=CBBBB1,299888601,PWHTZDUTEHXWHV-UHFFFAOYSA-N,144.238,-5.929,0,50,AAAA,NaN
3599,O[I+3](O)(O)O,1857524332,ZKOVUZXETKNFRX-UHFFFAOYSA-N,194.932,-5.224,0,50,AAAA,NaN
1033,OB1O[B-]2(O)OB(O)O[B-](O)(O1)O2,256882098,SNWLUPCUVMABOY-UHFFFAOYSA-N,191.271,-4.093,0,50,AAAA,in-vitro
1940,NC(=O)[C@H](O)[C@H](O)[C@H](O)[C@H](O)CO,104866619,JCZPMGDSEAFWDY-TXICZTDVSA-N,195.171,-4.092,0,50,AAAA,NaN
...,...,...,...,...,...,...,...,...,...
838,NC(=O)[C@H]1CCCNC1=O,5382647,INRMRRAPWZVXTQ-SCSAIBSYSA-N,142.158,-1.002,0,50,AAAA,NaN
1680,NC(=O)[C@@H]1CCCNC1=O,5382665,INRMRRAPWZVXTQ-BYPYZUCNSA-N,142.158,-1.002,0,50,AAAA,NaN
1551,Cc1[nH]c(=O)[nH]c(=O)c1CC(=O)O,182957,GFWWREGOTNQVGC-UHFFFAOYSA-N,184.151,-1.001,0,50,AAAA,biogenic
3381,NC(=O)[C@@H]1C=CCN1,4899483,JMUVYFOYOQNXDU-BYPYZUCNSA-N,112.132,-1.000,0,50,AAAA,in-vitro
3462,Nc1nn2c(=O)ccnc2[nH]1,105864751,REQIBELYMDQGNI-UHFFFAOYSA-N,151.129,-1.000,0,50,AAAA,NaN

In [4]:
df.sort_values(by='logp').head()

,smiles,zinc_id,inchikey,mwt,logp,reactive,purchasable,tranche_name,features
1012,[O-][I+3]([O-])([O-])O,1857621909,WXSIPUYRSBVXGK-UHFFFAOYSA-N,191.908,-7.120,0,50,AAAA,NaN
265,B1BBBBBC=CBBBB1,299888601,PWHTZDUTEHXWHV-UHFFFAOYSA-N,144.238,-5.929,0,50,AAAA,NaN
3599,O[I+3](O)(O)O,1857524332,ZKOVUZXETKNFRX-UHFFFAOYSA-N,194.932,-5.224,0,50,AAAA,NaN
1033,OB1O[B-]2(O)OB(O)O[B-](O)(O1)O2,256882098,SNWLUPCUVMABOY-UHFFFAOYSA-N,191.271,-4.093,0,50,AAAA,in-vitro
1940,NC(=O)[C@H](O)[C@H](O)[C@H](O)[C@H](O)CO,104866619,JCZPMGDSEAFWDY-TXICZTDVSA-N,195.171,-4.092,0,50,AAAA,NaN

In [5]:
import time

start_time = time.time()
df.sort_values(by='logp')
end_time = time.time()

print ('Time consumed:', end_time - start_time)

Time consumed: 0.008573532104492188

In [ ]:
'''
sorting은 정렬을 의미. 숫자를 정렬하는 방법.
kind 파라미터에서 sorting 알고리즘을 선택할 수 있습니다.
kind {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

sorting 방법별 설명
mergesort: https://gmlwjd9405.github.io/2018/05/08/algorithm-merge-sort.html
quicksort: https://gmlwjd9405.github.io/2018/05/10/algorithm-quick-sort.html
heapsort: https://gmlwjd9405.github.io/2018/05/10/algorithm-heap-sort.html
'''

#Quiz 1
# AAAA.txt 파일에서 sorting algorithm 별로 계산 속도를 계산하는 코드 작성

#sorting 알고리즘 옵션은 text로 입력하게 되어 있음. sorting 알고리즘 옵션 리스트 정의.
#for sorting_option in sorting알고리즘 옵션 리스트:
#    start_time 계산 시작 시간 기록
#    df에서 logp 컬럼을 지정된 sorting 알고리즘 (sorting_option)으로 정렬
#    end_time 계산 종료 시간 기록
#    print (end_time - start_time)

In [8]:
#Quiz2 zinc DB 전체에서 logP가 작은 5개의 물질 찾아내기
#Dask를 이용해서 sorting 작업 병렬화
import dask.dataframe as dd
from dask.distributed import Client

client = Client(n_workers=4)

C:\Users\user\miniconda3\Lib\site-packages\distributed\node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 62767 instead
  warnings.warn(

In [9]:
ddf = dd.read_csv("zinc_db/*.txt", sep='\t', usecols=['logp','smiles'])

# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nsmallest.html
# https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.nsmallest.html
result = ddf.nsmallest(5, 'logp').compute()

print("=== 최종 logP 하위 5개 물질 ===")
print(result)

=== 최종 logP 하위 5개 물질 ===
                                                 smiles    logp
74    O=P(OC/C1=C/BBBBBBBBBB1)(OC/C1=C/BBBBBBBBBB1)O... -17.491
1805  O=P(OCC1=CBBBBBBBBBB1)(OCC1=CBBBBBBBBBB1)OCC1=... -17.491
257   N[C@@H](C=O)[C@@H](O)[C@H](O[C@@H]1O[C@H](CO)[... -14.459
32    N[C@H](C=O)[C@H](O)[C@@H](O[C@H]1O[C@@H](CO)[C... -14.459
4     N[C@H]1[C@H](O[C@@H]2[C@@H](CO)O[C@@H](O[C@@H]... -14.302

In [10]:
client.close()